services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres_vector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: banco_vetorial
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: